### ISSUE TITLE
Consider adding our work into your great repo.

### ISSUE THREAD

**Issue by lxtGH** [YingqingHe/Awesome-LLMs-meet-Multimodal-Generation#1]
Hi! This is a great repo to record the LLM-based generation/editing.

Would you like to add our CVPR work into your repo and survey.

Towards Language-Driven Video Inpainting via Multimodal Large Language Models, CVPR-2024.

Arxiv: https://arxiv.org/abs/2401.10226

Code: https://github.com/jianzongwu/Language-Driven-Video-Inpainting

Project Page: https://jianzongwu.github.io/projects/rovi/

**Comment by YingqingHe** [comment]
> Hi! This is a great repo to record the LLM-based generation/editing.
> 
> Would you like to add our CVPR work into your repo and survey.
> 
> Towards Language-Driven Video Inpainting via Multimodal Large Language Models, CVPR-2024.
> 
> Arxiv: https://arxiv.org/abs/2401.10226
> 
> Code: https://github.com/jianzongwu/Language-Driven-Video-Inpainting
> 
> Project Page: https://jianzongwu.github.io/projects/rovi/

Hey thanks for your comments and your awesome work! We have added it to the repo!
