### ISSUE TITLE
Consider adding our work into your great repo.

### ISSUE THREAD

**Issue by wangqixun** [YingqingHe/Awesome-LLMs-meet-Multimodal-Generation#10]
优秀的repo！！！

您看看考虑添加我们这边的一些相关工作吗？有几个暂时还在写report

https://github.com/instantX-research

感谢感谢🙏🙏🙏

**Comment by YingqingHe** [comment]
> 优秀的repo！！！
> 
> 您看看考虑添加我们这边的一些相关工作吗？有几个暂时还在写report
> 
> https://github.com/instantX-research
> 
> 感谢感谢🙏🙏🙏

哈喽 谢谢！添加了贵组的几个工作！后面你们有新的工作也可以直接提交pull request，期待一波~
