### ISSUE TITLE
Consider cite the paper.

### ISSUE THREAD

**Issue by yuzhou914** [YingqingHe/Awesome-LLMs-meet-Multimodal-Generation#5]
Hi, thanks for the great survey. While please also consider cite paper "SmartEdit: Exploring Complex Instruction-based Image Editing with Multimodal Large Language Models", which is CVPR-2024 Highlight.  😂  😂  😂

**Comment by liu-zhy** [comment]
Thanks for your reminder. It is a great work! We will update the paper and add your work in our repo as soon as possible.
BTW, we also encourage you to pull a requst to our repo if you find some absent related works.

**Comment by YingqingHe** [comment]
> Hi, thanks for the great survey. While please also consider cite paper "SmartEdit: Exploring Complex Instruction-based Image Editing with Multimodal Large Language Models", which is CVPR-2024 Highlight. 😂 😂 😂

Yes! We will cite this paper in the next version of our arXiv paper and update it asap. Thank you!
