### ISSUE TITLE
Consider to our work into your great repo

### ISSUE THREAD

**Issue by YangLing0818** [YingqingHe/Awesome-LLMs-meet-Multimodal-Generation#9]
Hi! This is a great repo to record the LLM-based generation/editing.

Would you like to add our ICML work into your repo and survey.

Mastering Text-to-Image Diffusion: Recaptioning, Planning, and Generating with Multimodal LLMs, ICML 2024.

Arxiv: https://arxiv.org/abs/2401.11708

Code: https://github.com/YangLing0818/RPG-DiffusionMaster

**Comment by YingqingHe** [comment]
Thanks for your comment! We have added this great work!
